### ISSUE TITLE
Collisions with other trait methods

### ISSUE THREAD

**Issue by ghost** [ixudra/toggl#1]
Hi,

I'm trying to use your package with Laravel 5.4, but I constantly get the following error:
`Trait method project has not been applied because there are collisions with other trait methods on Ixudra\Toggl\TogglService`, what can I do to solve that?

Best regards,
Davide

**Comment by elimentz** [comment]
Not your fault, I will fix it :-)

**Comment by ghost** [comment]
@elimentz oh... thank you very much :)

**Comment by ghost** [comment]
Sorry, accidentally closed the issue

**Comment by elimentz** [comment]
Fixed. You can now collect project information using the `project()` method and collect a project report using the `projectReport()` method.

Apologies for the inconvenience, thanks for reporting the issue!

**Comment by ghost** [comment]
Thank you @elimentz for the promptly response and fix!
