### ISSUE TITLE
Recent baseUrl attribute change has broken reports methods

### ISSUE THREAD

**Issue by recycledbeans** [ixudra/toggl#20]
This commit introduced a bug that breaks reports methods since the reports endpoints start with /reports/api instead of /api: [2ba7bb0b61ce345ec57baf57204c0ce45264aea6](https://github.com/ixudra/toggl/commit/2ba7bb0b61ce345ec57baf57204c0ce45264aea6)

PR #19 should fix this, but I wanted to make sure the problem was flagged as an issue.

**Comment by elimentz** [comment]
PR merged, issue solved. Thx for letting me know.
